#!/bin/bash

_puid=$(printenv PUID)
_pgid=$(printenv PGID)

cloud_encrypt_dir="/cloud-encrypt"
cloud_decrypt_dir="/cloud-decrypt"

local_decrypt_dir="/local-decrypt"
local_media_dir="/local-media"

rclone_cache_chunk_path="/chunks"
rclone_cache_db_path="/chunks/db"

rclone_config="--config=/config/rclone.conf"
rclone_options="${rclone_config} --buffer-size $(printenv BUFFER_SIZE) --checkers $(printenv CHECKERS) --cache-writes"
rclone_cache_options="--cache-chunk-size $(printenv CACHE_CHUNK_SIZE) --cache-total-chunk-size $(printenv CACHE_TOTAL_CHUNK_SIZE) --cache-info-age $(printenv CACHE_INFO_AGE) --cache-workers $(printenv CACHE_WORKERS) --cache-chunk-path ${rclone_cache_chunk_path} --cache-db-path ${rclone_cache_db_path}"
rclone_mount_options="${rclone_options} ${rclone_cache_options} --allow-non-empty --allow-other --uid ${_puid:-911} --gid ${_pgid:-911}"

if [ "$(printenv READ_ONLY)" != "0" ]; then
    rclone_mount_options="${rclone_mount_options} --read-only"
fi

ufs_options="-o uid=${_puid:-911} -o gid=${_pgid:-911} -o cow,allow_other,direct_io,nonempty,auto_cache,sync_read"

log_dir="/log"
if [ ! -d "${log_dir}" ]; then
	mkdir -p "${log_dir}"
fi
