#!/bin/bash

_puid=$(printenv PUID)
_pgid=$(printenv PGID)

cloud_encrypt_dir="/cloud-encrypt"
cloud_decrypt_dir="/cloud-decrypt"

local_decrypt_dir="/local-decrypt"
local_media_dir="/local-media"

rclone_config="--config=/config/rclone.conf"
rclone_exclude_file="/config/exclude.txt"
rclone_options="${rclone_config} --buffer-size $(printenv BUFFER_SIZE) --checkers $(printenv CHECKERS)"
rclone_mirror_options="${rclone_config} --exclude-from=${rclone_exclude_file}"
rclone_mount_options="${rclone_options} --allow-non-empty --allow-other --uid ${_puid:-911} --gid ${_pgid:-911}"

if [ "$(printenv READ_ONLY)" != "0" ]; then
  rclone_mount_options="${rclone_mount_options} --read-only"
  plexdrive_options="${plexdrive_options} -o read_only"
fi

if [ "$(printenv RCLONE_VERBOSE)" != "0" ]; then
  rclone_mirror_options="${rclone_mirror_options} --verbose"
  rclone_mount_options="${rclone_mount_options} --verbose"
fi

if [ "$(printenv CACHE_PROGRAM)" == "plexdrive" ]; then
  plexdrive_temp_dir="/chunks"
  plexdrive_cache_bolt="/chunks/cache.bolt"
  plexdrive_options="mount --config=/config --cache-file=${plexdrive_cache_bolt} --chunk-size=$(printenv CHUNK_SIZE) --chunk-check-threads=$(printenv CHUNK_CHECK_THREADS) --chunk-load-ahead=$(printenv CHUNK_LOAD_AHEAD) --chunk-load-threads=$(printenv CHUNK_LOAD_THREADS) --max-chunks=$(printenv MAX_CHUNKS) --uid=${_puid:-911} --gid=${_pgid:-911} -o allow_other"
fi

if [ "$(printenv CACHE_PROGRAM)" == "rclone" ]; then
  rclone_cache_chunk_path="/chunks"
  rclone_cache_db_path="/chunks/db"
  rclone_options="${rclone_options} --cache-writes"
  rclone_cache_options="--cache-chunk-size $(printenv CACHE_CHUNK_SIZE) --cache-total-chunk-size $(printenv CACHE_TOTAL_CHUNK_SIZE) --cache-info-age $(printenv CACHE_INFO_AGE) --cache-workers $(printenv CACHE_WORKERS) --cache-chunk-path ${rclone_cache_chunk_path} --cache-db-path ${rclone_cache_db_path}"
fi

if [ ! -f "${rclone_exclude_file}" ]; then
  touch ${rclone_exclude_file}
fi

ufs_options="-o uid=${_puid:-911} -o gid=${_pgid:-911} -o cow,allow_other,direct_io,nonempty,auto_cache,sync_read"

log_dir="/log"
if [ ! -d "${log_dir}" ]; then
	mkdir -p "${log_dir}"
fi
